SET FOREIGN_KEY_CHECKS = 0;

-- popular tabela de usuários
TRUNCATE usuarios;

INSERT INTO
    usuarios (nome, email, senha,  role, criado_em, atualizado_em)
VALUES
    ('Aluno Teste', 'aluno@pucrs.br', '$2a$04$4vwa/ugGbBVDvbWaKUVZBuJbjyQyj6tqntjSmG8q.hi97.xSdhj/2', 'ALUNO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Aluno Teste 2', 'aluno2@pucrs.br', '$2a$04$4vwa/ugGbBVDvbWaKUVZBuJbjyQyj6tqntjSmG8q.hi97.xSdhj/2', 'ALUNO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Coordenador Teste', 'coordenador@pucrs.br', '$2a$04$4vwa/ugGbBVDvbWaKUVZBuJbjyQyj6tqntjSmG8q.hi97.xSdhj/2', 'COORDENADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- popular tabela de disciplinas
TRUNCATE disciplinas;

INSERT INTO
    disciplinas (nome, codigo, creditos, criado_em, atualizado_em)
VALUES
    ('FUNDAMENTOS DE PROGRAMAÇÃO', '4611C-06', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('INTRODUÇÃO A SISTEMAS DE INFORMAÇÃO', '4636U-04', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PROJETO E DESENVOLVIMENTO DE SOFTWARE', '4637C-04', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENGENHARIA DE SOFTWARE', '4636F-02', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TEORIA DA COMPUTAÇÃO', '4637J-02', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- popular tabela de turmas
TRUNCATE turmas;

INSERT INTO
    turmas (nome, disciplina_id, ano, semestre, horarios, vagas, criado_em, atualizado_em)
VALUES
    ('Turma 128', 1, 2019, 1, '["2AB", "4AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 129', 1, 2021, 2, '["2AB", "4AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 130', 1, 2022, 1, '["2AB", "4AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 131', 1, 2022, 2, '["2AB", "4AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 230', 2, 2021, 2, '["3AB", "5AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 231', 2, 2022, 1, '["3AB", "5AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 232', 2, 2022, 2, '["3AB", "5AB"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 333', 3, 2021, 1, '["4CD", "6CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 340', 3, 2021, 2, '["4CD", "6CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 341', 3, 2022, 1, '["4CD", "6CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 344', 3, 2022, 2, '["4CD", "6CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 420', 4, 2022, 1, '["2CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 422', 4, 2022, 2, '["2CD"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 512', 5, 2018, 1, '["4JK"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 510', 5, 2019, 2, '["4JK"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 525', 5, 2021, 2, '["4JK"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 530', 5, 2022, 1, '["4LM"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turma 535', 5, 2022, 2, '["4LM"]',30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- popular tabela de historicos
TRUNCATE historicos;

INSERT INTO
    historicos (aluno_id, turma_id, status, criado_em, atualizado_em, nota)
VALUES
    (1, 4, "CURSANDO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null),
    (1, 7, "CURSANDO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null),
    (1, 11, "CURSANDO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null),
    (2, 7, "CURSANDO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null),
    (2, 10, "CURSANDO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null),
    (1, 1, "REPROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4.5),
    (2, 1, "REPROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4.7),
    (2, 5, "REPROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4.8),
    (1, 5, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7.5),
    (1, 9, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8.4),
    (1, 15, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10.0),
    (2, 6, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7.5),
    (2, 10, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9.4),
    (2, 14, "APROVADO", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8.9);

SET FOREIGN_KEY_CHECKS = 1;